### ISSUE TITLE
More than one hash calculator windows open crashes

### ISSUE THREAD

**Issue by Soniczac7** [Soniczac7/Download-Manager#9]
**Describe the bug**
When there are no debuggers connected and more than one hash calculator windows open the program crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build
2. Open the program with no debugger attached
3. Open more than one hash calculator window
4. See crash with no error

**Expected behaviour**
Program does not crash on opening more than one hash calculator windows.

**Comment by Soniczac7** [comment]
Update: The crash occurred with a debugger attached.
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
StackTrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 6919
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 6426
   at System.Windows.Forms.Control.Invoke(Delegate method) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 6407
   at DownloadManager.HashCalculator.ShowProgressBar(Boolean show) in D:\DownloadManager\HashCalculator.cs:line 184
   at DownloadManager.HashCalculator.<>c__DisplayClass4_0.<.ctor>b__0() in D:\DownloadManager\HashCalculator.cs:line 39
   at System.Threading.Thread.StartHelper.Callback(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs:line 42
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 183
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 207
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105

**Comment by Soniczac7** [comment]
The issue will be fixed in version 4.0.0.0.
